<a href="https://colab.research.google.com/github/rkaur050/Numpy-vs-Python-List/blob/main/Array_vs_List.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##1. Array v/s List Comparision

In [8]:
import numpy as np
arr=np.array([1,3,2])
lst=[1,3,2]
print(lst,type(lst),arr,type(arr),sep='\n')
print(lst==arr)
print(arr.tolist()==lst)
print(type(arr.tolist()))
print(sorted(arr.tolist())==sorted(lst))

[1, 2, 3]
<class 'list'>
[1 3 2]
<class 'numpy.ndarray'>
[ True False False]
False
<class 'list'>
True


##2. Adding elements

In [22]:
lst=[1,3,2]
arr=np.array([1,2,3])
print(lst)
lst.append(4)
print(lst)
print('-'*5)
print(arr)
np.append(arr,4)
print(arr)
arr=np.append(arr,4)
print(arr)

[1, 3, 2]
[1, 3, 2, 4]
-----
[1 2 3]
[1 2 3]
[1 2 3 4]


##3. Removing elements

In [28]:
lst=[1,3,2]
arr=np.array([1,2,3])
print(lst)
del lst[-2]
print(lst)
print('-'*5)
print(arr)
arr=np.delete(arr,-2)
print(arr)

[1, 3, 2]
[1, 2]
-----
[1 2 3]
[1 3]


##4. Updating elements

In [33]:
lst=[1,3,2]
print(lst)
lst[1]=5
lst[-1]=4
print(lst)
print('-'*5)
arr=np.array([1,2,3])
print(arr)
arr[-3]=4
arr[1]=5
print(arr)

[1, 3, 2]
[1, 5, 4]
-----
[1 2 3]
[4 5 3]


##5. Searching Comparision

In [44]:
import time

my_lst=list(range(10000000))
my_arr=np.arange(10000000)

start_time=time.time()
for i in range(100):
  if 50000000 in my_lst:
    pass

end_time=time.time()
print('List:',end_time-start_time)
print('-'*5)
start_time=time.time()
for i in range(100):
  if 50000000 in my_arr:
    pass
end_time=time.time()
print('Array:',end_time-start_time)

List: 11.75109601020813
-----
Array: 1.0857665538787842
